donation:
  food:
    expiration_in_days: 45
server:
  port: 8084
spring:
  application:
    name: donations-service
  security:
    jackson:
      serialization:
        write-dates-as-timestamps: false
      deserialization:
        accept-single-value-as-array: true
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_DONATIONS_CLIENT_ID}
            client-secret: ${KEYCLOAK_DONATIONS_CLIENT_SECRET}
            scope: openid
        provider:
          keycloak:
            realm: ${KEYCLOAK_REALM:test}
            server-url: ${KEYCLOAK_URL:http://localhost:8181}
            token-uri: ${KEYCLOAK_URL:http://localhost:8181}/realms/master/protocol/openid-connect
            user-info-uri: ${KEYCLOAK_URL:http://localhost:8181}/realms/master/protocol/openid-connect/userinfo
            issuer-uri: ${KEYCLOAK_URL:http://localhost:8181}/realms/master
            jwk-set-uri: ${KEYCLOAK_URL:http://localhost:8181}/realms/master/protocol/openid-connect/certs
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8181}/realms/master
          jwk-set-uri: ${KEYCLOAK_URL:http://localhost:8181}/realms/master/protocol/openid-connect/certs
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    driverClassName: com.mysql.cj.jdbc.Driver
    password: harera
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/hayat?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
  hibernate:
    connection:
      charSet: UTF-8
      characterEncoding: utf8
      useUnicode: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: false
  liquibase:
    change-log: classpath:db/main/changelog/changelog-main.yaml
    clear-checksums: true
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka/
